name: release-www
on:
  push:
    branches:
      - main
    paths:
      - 'www/**'

defaults:
  run:
    working-directory: www

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install pnpm -g --slient
      - name: Install
        run: |
          pnpm install --silent
      - name: Validate
        run: |
          pnpm validate
      - name: Build
        run: |
          pnpm build
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: |
          aws s3 sync build s3://${BUCKET}/ \
            --acl public-read \
            --delete \
            --exclude service-worker.js \
            --exclude index.html
          aws s3 cp build/index.html s3://${BUCKET}/index.html \
            --acl public-read \
            --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type text/html \
            --metadata-directive REPLACE
        env:
          BUCKET: www-defiverr
